### ISSUE TITLE
Black edits being deferred by Nova during save operations

### ISSUE THREAD

**Issue by Anton-2** [flother/Blake.novaextension#1] opened 2020-09-27 10:16 UTC
Blake process is asynchronous, and acts on the editor's buffer, but nova will save the file before Blake's actions.
You see the file after Blake's edit, but the file saved is the previous version.
This led to strange flake reports on formatting issues, as flake8 will read the saved file, but report it on the version corrected by Blake, which is correct.
 
I didn't find any way to tell nova to wait for the end of edit before saving, so I don't know if it can work correctly with the current nova API.

**Comment by flother** [comment] 2020-09-28 14:01
Thanks for creating an issue for this. It's always a pleasure to hear that people are using things I make.

[Blake shells out to a Black process within an `editor.onWillSave()` callback](https://github.com/flother/Blake.novaextension/blob/b1e4d7a48ba44673c306597d4adb456f7740b01e/Scripts/main.js#L17-L20). The Nova docs say that:

> If the callback performs modifications to the editor within the callback (such as with `edit()`), they will be applied in such a way as to include them in the pending save operation. If a callback registered using this method takes too long to perform operations, any edits enqueued may be deferred until after the save operation, or discarded entirely. ([source](https://docs.nova.app/api-reference/text-editor/#onwillsave-callback))

Blake does [alter the document using an `edit()` callback](https://github.com/flother/Blake.novaextension/blob/b1e4d7a48ba44673c306597d4adb456f7740b01e/Scripts/Formatter.js#L15-L17), as the docs suggest, and so Blake's edits should be included in save operations. But, as you've noticed, they aren't: as well as the mismatch with Flake8 issues, the document is also marked as unsaved after Black's changes have been applied.

There's no mention of how long is "too long", but I think the process of running Black within a shell is taking too long to return, and so the edits are being deferred. I'll have to rethink how I'm running Flake8 and Black on save, perhaps try and run them synchronously one after the other, using Black's output as input to Flake8.

**Comment by Anton-2** [comment] 2020-09-28 16:37
And thanks for creating this...

I've tried to make the black round-trip faster, by using blackd and just POST'ing a request, but this is still not fast enough.
I suspect that anything doing IO will take "too long"...

To implement a true "format before save" option, we need to have a way in nova's API to defer save until all edits are done. I've asked Panic support about this.

**Comment by edwardloveall** [comment] 2021-07-25 20:46
I don't think it's the time it takes to run black. From the Nova docs for [`onWillSave`](https://docs.nova.app/api-reference/text-editor/#onwillsavecallback-thisvalue):

> the runtime guarantees that it will allow at least 5 seconds for all extensions to perform their operations.

Black is definitely not taking that long! 😅 

The problem is that `onWillSave` needs to return a `Promise` if you want it to wait:

> This method may return a `Promise` object to denote to the runtime that changes need to be performed asynchronously.

Right now, the `onWillSave` callback [doesn't return anything](https://github.com/flother/Blake.novaextension/blob/master/Scripts/main.js#L19). The BlackProcess does its work in the background and [when it completes](https://github.com/flother/Blake.novaextension/blob/master/Scripts/BlackProcess.js#L69) without any errors, it [alters the document](https://github.com/flother/Blake.novaextension/blob/master/Scripts/Formatter.js#L18-L20). But by the time this has happened, onWillSave is already done since it didn't know to wait.

I've been understanding this through an extension I'm working on and I'd be happy to take a crack at making it work here. However, playing around with the code a little, I believe it will be a significant refactor of at least `BlackProcess` and likely to `Formatter` as well so I didn't want to give it a go without checking first.

**Comment by edwardloveall** [comment] 2021-07-25 22:53
I ended up making these changes in #4. Even if they don't get merged, we can at least see what it might look like.

**Closed as completed** 2023-01-05 21:56 UTC
